[project]
name = "playlist-watch"
version = "0.1.0"
description = "watch spotify playlist for updates"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord>=2.3.2",
    "pytz>=2025.1",
    "requests>=2.32.3",
]
